version: "3.8"

services:
  redis:
    image: redis:7
    container_name: disqueue_redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: disqueue_api
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}
      - PYTHONPATH=/app
    ports:
      - "${API_PORT}:8000"
    volumes:
      - .:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: disqueue_worker
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: python worker/worker.py
